"""add enemy_drops table

Revision ID: 6dd1b9c3be01
Revises: b1b9e5ae3995
Create Date: 2026-03-25 01:20:22.478547

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6dd1b9c3be01"
down_revision: str | Sequence[str] | None = "b1b9e5ae3995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
