"""initial schema

Revision ID: 6f76809a3c2f
Revises:
Create Date: 2026-03-17 11:32:41.664254

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f76809a3c2f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "armor",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description_fr", sa.String(length=500), nullable=False),
        sa.Column("wep_file_id", sa.Integer(), nullable=False),
        sa.Column("armor_type", sa.String(length=50), nullable=False),
        sa.Column("str", sa.Integer(), nullable=False),
        sa.Column("int", sa.Integer(), nullable=False),
        sa.Column("agi", sa.Integer(), nullable=False),
        sa.Column("gem_slots", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consumables",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description_fr", sa.String(length=500), nullable=False),
        sa.Column("effects", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gems",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description_fr", sa.String(length=500), nullable=False),
        sa.Column("magnitude", sa.String(length=50), nullable=False),
        sa.Column("affinity_type", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grips",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description_fr", sa.String(length=500), nullable=False),
        sa.Column("wep_file_id", sa.Integer(), nullable=False),
        sa.Column("grip_type", sa.Integer(), nullable=False),
        sa.Column("str", sa.Integer(), nullable=False),
        sa.Column("int", sa.Integer(), nullable=False),
        sa.Column("agi", sa.Integer(), nullable=False),
        sa.Column("dp", sa.Integer(), nullable=True),
        sa.Column("pp", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("str_modifier", sa.Integer(), nullable=False),
        sa.Column("int_modifier", sa.Integer(), nullable=False),
        sa.Column("agi_modifier", sa.Integer(), nullable=False),
        sa.Column("human", sa.Integer(), nullable=False),
        sa.Column("beast", sa.Integer(), nullable=False),
        sa.Column("undead", sa.Integer(), nullable=False),
        sa.Column("phantom", sa.Integer(), nullable=False),
        sa.Column("dragon", sa.Integer(), nullable=False),
        sa.Column("evil", sa.Integer(), nullable=False),
        sa.Column("fire", sa.Integer(), nullable=False),
        sa.Column("water", sa.Integer(), nullable=False),
        sa.Column("wind", sa.Integer(), nullable=False),
        sa.Column("earth", sa.Integer(), nullable=False),
        sa.Column("light", sa.Integer(), nullable=False),
        sa.Column("dark", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weapons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description_fr", sa.String(length=500), nullable=False),
        sa.Column("wep_file_id", sa.Integer(), nullable=False),
        sa.Column("blade_type", sa.String(length=50), nullable=False),
        sa.Column("damage_type", sa.String(length=50), nullable=False),
        sa.Column("risk", sa.Integer(), nullable=False),
        sa.Column("str", sa.Integer(), nullable=False),
        sa.Column("int", sa.Integer(), nullable=False),
        sa.Column("agi", sa.Integer(), nullable=False),
        sa.Column("range", sa.Integer(), nullable=False),
        sa.Column("damage", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weapons")
    op.drop_table("materials")
    op.drop_table("grips")
    op.drop_table("gems")
    op.drop_table("consumables")
    op.drop_table("armor")
    # ### end Alembic commands ###
