"""add crafting and material recipes

Revision ID: b0d0c8bef8bc
Revises: 6f76809a3c2f
Create Date: 2026-03-17 14:06:25.620975

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0d0c8bef8bc'
down_revision: str | Sequence[str] | None = '6f76809a3c2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crafting_recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=False),
    sa.Column('input_1', sa.String(length=100), nullable=False),
    sa.Column('input_2', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=False),
    sa.Column('tier_change', sa.Integer(), nullable=False),
    sa.Column('has_swap', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crafting_recipes_category'), 'crafting_recipes', ['category'], unique=False)
    op.create_index(op.f('ix_crafting_recipes_input_1'), 'crafting_recipes', ['input_1'], unique=False)
    op.create_index(op.f('ix_crafting_recipes_input_2'), 'crafting_recipes', ['input_2'], unique=False)
    op.create_index(op.f('ix_crafting_recipes_result'), 'crafting_recipes', ['result'], unique=False)
    op.create_index(op.f('ix_crafting_recipes_sub_category'), 'crafting_recipes', ['sub_category'], unique=False)
    op.create_table('material_recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=False),
    sa.Column('input_1', sa.String(length=100), nullable=False),
    sa.Column('input_2', sa.String(length=100), nullable=False),
    sa.Column('material_1', sa.String(length=50), nullable=False),
    sa.Column('material_2', sa.String(length=50), nullable=False),
    sa.Column('result_material', sa.String(length=50), nullable=False),
    sa.Column('tier_change', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_recipes_category'), 'material_recipes', ['category'], unique=False)
    op.alter_column('consumables', 'effects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consumables', 'effects',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_material_recipes_category'), table_name='material_recipes')
    op.drop_table('material_recipes')
    op.drop_index(op.f('ix_crafting_recipes_sub_category'), table_name='crafting_recipes')
    op.drop_index(op.f('ix_crafting_recipes_result'), table_name='crafting_recipes')
    op.drop_index(op.f('ix_crafting_recipes_input_2'), table_name='crafting_recipes')
    op.drop_index(op.f('ix_crafting_recipes_input_1'), table_name='crafting_recipes')
    op.drop_index(op.f('ix_crafting_recipes_category'), table_name='crafting_recipes')
    op.drop_table('crafting_recipes')
    # ### end Alembic commands ###
