"""add gem stats and consumable descriptions

Revision ID: bdd18c7d04d7
Revises: cd8fb71e975b
Create Date: 2026-03-19 22:00:32.020547

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdd18c7d04d7"
down_revision: str | Sequence[str] | None = "cd8fb71e975b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consumables", sa.Column("description", sa.Text(), server_default="", nullable=False)
    )
    op.add_column("gems", sa.Column("description", sa.Text(), server_default="", nullable=False))
    op.add_column("gems", sa.Column("gem_type", sa.String(length=50), nullable=False))
    op.add_column("gems", sa.Column("str", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("int", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("agi", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("human", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("beast", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("undead", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("phantom", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("dragon", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("evil", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("physical", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("fire", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("water", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("wind", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("earth", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("light", sa.Integer(), server_default="0", nullable=False))
    op.add_column("gems", sa.Column("dark", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gems", "dark")
    op.drop_column("gems", "light")
    op.drop_column("gems", "earth")
    op.drop_column("gems", "wind")
    op.drop_column("gems", "water")
    op.drop_column("gems", "fire")
    op.drop_column("gems", "physical")
    op.drop_column("gems", "evil")
    op.drop_column("gems", "dragon")
    op.drop_column("gems", "phantom")
    op.drop_column("gems", "undead")
    op.drop_column("gems", "beast")
    op.drop_column("gems", "human")
    op.drop_column("gems", "agi")
    op.drop_column("gems", "int")
    op.drop_column("gems", "str")
    op.drop_column("gems", "gem_type")
    op.drop_column("gems", "description")
    op.drop_column("consumables", "description")
    # ### end Alembic commands ###
