"""add armor affinities and resistances

Revision ID: f6d096e20deb
Revises: 3fa77c8fddd5
Create Date: 2026-03-19 01:02:49.151409

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6d096e20deb'
down_revision: str | Sequence[str] | None = '3fa77c8fddd5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armor', sa.Column('human', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('beast', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('undead', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('phantom', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('dragon', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('evil', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('fire', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('water', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('wind', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('earth', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('light', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('dark', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('blunt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('edged', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('piercing', sa.Integer(), server_default='0', nullable=False))
    op.add_column('armor', sa.Column('physical', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('armor', 'physical')
    op.drop_column('armor', 'piercing')
    op.drop_column('armor', 'edged')
    op.drop_column('armor', 'blunt')
    op.drop_column('armor', 'dark')
    op.drop_column('armor', 'light')
    op.drop_column('armor', 'earth')
    op.drop_column('armor', 'wind')
    op.drop_column('armor', 'water')
    op.drop_column('armor', 'fire')
    op.drop_column('armor', 'evil')
    op.drop_column('armor', 'dragon')
    op.drop_column('armor', 'phantom')
    op.drop_column('armor', 'undead')
    op.drop_column('armor', 'beast')
    op.drop_column('armor', 'human')
    # ### end Alembic commands ###
